apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo
  labels:
    app: test
spec:
  replicas: 3
  selector:
    matchLabels:
      app: test
  template:
    metadata:
      labels:
        app: test
    spec:
      containers:
      - name: demo
        image: demo:1.14.2
        ports:
        - containerPort: 80
